### ISSUE TITLE
Add toggle for fullscreen mode

### ISSUE THREAD

**Issue by thinkmassive** [thinkmassive/screenlit#1]
Clicking a new color makes the site go fullscreen, which can be annoying. Make the fullscreen a separate toggle, independent from color selection.

**Comment by thebrandonlucas** [comment]
Let me know if you want this toggle styled differently!

https://github.com/thinkmassive/screenlit/pull/2

**Comment by thinkmassive** [comment]
Wow, that was _FAST!!_

Thank you so much for the fix, the new "fullscreen" link looks great!
